# -*- coding: utf-8 -*-
"""Rene_Dvash_Tagreed_Assi_ex1_version2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1moOtaClEaTo4L79UahlP11nKmcvYHwlb

רנה דבש 213468200
תגריד עאצי 213232895
optional size: 21 13 34 46 68 82 20 32 23 28 89 95
"""

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, regularizers

# 1. Load and Preprocess CIFAR-10 Data
(x_train, y_train), (x_test, y_test) = keras.datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

# Convert labels to one-hot encoding
num_classes = 10
y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)

# Split training data into training and validation sets
validation_split = 0.2  # Use 20% of the training data for validation
split_index = int(len(x_train) * (1 - validation_split))
x_val, y_val = x_train[split_index:], y_train[split_index:]
x_train_new, y_train_new = x_train[:split_index], y_train[:split_index]

# Get the input shape
input_shape = x_train_new.shape[1:]

# 2. Define the Model Architecture & Create the Model Instance

model = keras.Sequential([
layers.Input(shape=input_shape),

layers.Conv2D(32, (3, 3), padding='same', activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.Conv2D(32, (3, 3), padding='same', activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.MaxPooling2D((2, 2)),
layers.Dropout(0.1),

layers.Conv2D(68, (3, 3), padding='same', activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.Conv2D(68, (3, 3), padding='same', activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.MaxPooling2D((2, 2)),
layers.Dropout(0.2),

layers.Conv2D(82, (3, 3), padding='same', activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.MaxPooling2D((2, 2)),
layers.Dropout(0.3),

layers.Flatten(),
layers.Dense(89, activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.Dense(89, activation='relu',kernel_regularizer=regularizers.l2(0.001)),
layers.BatchNormalization(),
layers.Dropout(0.4),
layers.Dense(num_classes, activation='softmax'),
])
model.summary()

# 3. Compile the Model
model.compile(optimizer='sgd',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# 4. Train the Model with Validation Data
epochs = 20
batch_size = 128

history = model.fit(x_train_new, y_train_new,
                    epochs=epochs,
                    batch_size=batch_size,
                    validation_data=(x_val, y_val))

# 5. Evaluate the Model on the Test Set
test_loss, test_accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f"Test Loss: {test_loss:.3f}")
print(f"Test Accuracy: {test_accuracy:.3f}")

# Print Final Validation Metrics
val_loss, val_accuracy = model.evaluate(x_val, y_val, verbose=0)
print(f"Validation Loss: {val_loss:.3f}")
print(f"Validation Accuracy: {val_accuracy:.3f}")

# Print Final Training Metrics
train_loss, train_accuracy = model.evaluate(x_train_new, y_train_new, verbose=0)
print(f"Training Loss: {train_loss:.3f}")
print(f"Training Accuracy: {train_accuracy:.3f}")

# 6. Visualize Training and Validation Performance
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 2)
plt.plot(history.history['loss'], label='Train Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.grid(True)
plt.legend()

plt.subplot(1, 2, 1)
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Accuracy over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.grid(True)
plt.legend()

plt.tight_layout()

plt.show()
